change compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,6 +5,8 @@
 #     $ bin/compile <build-dir> <cache-dir>
 
 
+# Fail fast and fail hard.
+set -eo pipefail
 
 # Prepend proper path for virtualenv hackery. This will be deprecated soon.
 export PATH=:/usr/local/bin:$PATH
@@ -16,6 +18,17 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 
 CACHED_DIRS=".heroku"
+
+# Static configurations for virtualenv caches.
+VIRTUALENV_LOC=".heroku/venv"
+LEGACY_TRIGGER="lib/python2.7"
+PROFILE_PATH="$BUILD_DIR/.profile.d/python.sh"
+
+# Python version. This will be used in the future to specify custom Pythons.
+DEFAULT_PYTHON_VERSION="python-2.7.4"
+PYTHON_EXE="/app/.heroku/python/bin/python"
+PIP_VERSION="1.3.1"
+DISTRIBUTE_VERSION="0.6.36"
 
 # Sanitizing environment variables.
 unset GIT_DIR PYTHONHOME PYTHONPATH LD_LIBRARY_PATH LIBRARY_PATH
@@ -54,10 +67,24 @@ cd $BUILD_DIR
 # Experimental pre_compile hook.
 source $BIN_DIR/steps/hooks/pre_compile
 
+# If no requirements given, assume `setup.py develop`.
+if [ ! -f requirements.txt ]; then
+  puts-step "No requirements.txt provided; assuming dist package."
+  echo "-e ." > requirements.txt
+fi
+
+# If no runtime given, assume default version.
+if [ ! -f runtime.txt ]; then
+  puts-step "No runtime.txt provided; assuming $DEFAULT_PYTHON_VERSION."
+  echo $DEFAULT_PYTHON_VERSION > runtime.txt
+fi
 
 # ### The Cache
 mkdir -p $CACHE_DIR
 
+# Purge "old-style" virtualenvs.
+[ -d $CACHE_DIR/$LEGACY_TRIGGER ] && rm -fr $CACHE_DIR/.heroku/bin $CACHE_DIR/.heroku/lib $CACHE_DIR/.heroku/include
+[ -d $CACHE_DIR/$VIRTUALENV_LOC ] && rm -fr $CACHE_DIR/.heroku/venv $CACHE_DIR/.heroku/src
 
 # Restore old artifacts from the cache.
 for dir in $CACHED_DIRS; do
@@ -69,13 +96,56 @@ set +e
 mkdir .heroku &> /dev/null
 set -e
 
-# mkdir -p $(dirname $PROFILE_PATH)
+mkdir -p $(dirname $PROFILE_PATH)
 
 set +e
+PYTHON_VERSION=$(cat runtime.txt)
+
+# Install Python.
+if [ -f .heroku/python-version ]; then
+  if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
+    puts-step "Found $(cat .heroku/python-version), removing."
+    rm -fr .heroku/python
+  else
+    SKIP_INSTALL=1
+  fi
+fi
 
 
+if [ ! "$SKIP_INSTALL" ]; then
+  puts-step "Preparing Python runtime ($PYTHON_VERSION)"
+  curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
+  if [[ $? != 0 ]] ; then
+    puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
+    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+    exit 1
+  fi
+  mv python .heroku/python
 
+  # Record for future reference.
+  echo $PYTHON_VERSION > .heroku/python-version
+  FRESH_PYTHON=true
 
+  hash -r
+else
+  puts-step "Using Python runtime ($PYTHON_VERSION)"
+fi
+
+# If Pip isn't up to date:
+# if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_VERSION* ]]; then
+#   WORKING_DIR=$(pwd)
+#
+#   # Prepare it for the real world
+#   puts-step "Installing Distribute ($DISTRIBUTE_VERSION)"
+#   cd $ROOT_DIR/vendor/distribute-$DISTRIBUTE_VERSION/
+#   python setup.py install &> /dev/null
+#   cd $WORKING_DIR
+#
+#   puts-step "Installing Pip ($PIP_VERSION)"
+#   cd $ROOT_DIR/vendor/pip-$PIP_VERSION/
+#   python setup.py install &> /dev/null
+#   cd $WORKING_DIR
+# fi
 
 set -e
 hash -r
@@ -97,6 +167,10 @@ if (grep -Fiq "hg+" requirements.txt) then
   /app/.heroku/python/bin/pip install --use-mirrors mercurial | cleanup | indent
 fi
 
+# Install dependencies with Pip.
+puts-step "Installing dependencies using Pip ($PIP_VERSION)"
+# /app/.heroku/python/bin/pip install --use-mirrors -r requirements.txt --exists-action=w --src=./.heroku/src | cleanup | indent
+
 
 # Load enviornment variables in ENV_DIR into the
 # enviornment, because manage.py will need them
@@ -112,6 +186,16 @@ if [ -d "$env_dir" ]; then
   done
 fi
 
+
+# Database migrations
+# source $BIN_DIR/steps/syncdb
+
+# Django collectstatic support.
+# source $BIN_DIR/steps/compress
+# source $BIN_DIR/steps/collectstatic
+
+# ### Finalize
+#
 
 # Set context environment variables.
 set-env PATH '$HOME/.heroku/python/bin:/app/vendor/pdf2htmlEX/bin:$PATH'
